<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Role Matrix PHN</title>
    <style>
        * { box-sizing: border-box; }
        @page { margin: 110px 18px 62px; }
        body { font-family: DejaVu Sans, sans-serif; color: #111827; margin: 0; font-size: 11px; }
        .fixed-header { position: fixed; top: -94px; left: 0; right: 0; }
        .fixed-footer { position: fixed; bottom: -46px; left: 0; right: 0; }
        .header { border: 2px solid #111827; border-radius: 8px; padding: 10px 12px; }
        .header-row { width: 100%; border-collapse: collapse; }
        .header-row td { border: none; padding: 0; vertical-align: middle; }
        .logo-cell { width: 160px; }
        .logo { width: 150px; height: auto; display: block; }
        .brand { font-size: 16px; font-weight: 700; margin-bottom: 2px; }
        .tagline { font-size: 9px; color: #374151; margin-bottom: 5px; }
        .meta { font-size: 10px; color: #4b5563; }
        .title { margin: 12px 0 8px; font-size: 12px; font-weight: 700; background: #f9fafb; padding: 6px 8px; border: 1px solid #d1d5db; border-radius: 6px; }
        table { width: 100%; border-collapse: collapse; table-layout: fixed; }
        th, td { border: 1px solid #d1d5db; padding: 5px; vertical-align: top; word-wrap: break-word; }
        th { background: #f3f4f6; font-size: 10px; text-align: left; }
        td { font-size: 10px; }
        .small { font-size: 9px; color: #374151; }
        .badge { display: inline-block; padding: 1px 4px; border-radius: 3px; border: 1px solid #d1d5db; font-size: 8px; margin-right: 2px; margin-top: 2px; }
        .section-break { page-break-inside: avoid; margin-bottom: 10px; }
        .module-name { text-transform: uppercase; }
        .yes { color: #047857; font-weight: 700; }
        .no { color: #b91c1c; font-weight: 700; }
        .watermark { position: fixed; top: 46%; left: 50%; transform: translate(-50%, -50%) rotate(-26deg); font-size: 64px; color: rgba(148, 163, 184, 0.13); font-weight: 700; letter-spacing: 3px; white-space: nowrap; z-index: -1; }
        .footer-box { border-top: 1px solid #9ca3af; padding-top: 4px; font-size: 9px; color: #4b5563; display: flex; justify-content: space-between; gap: 10px; }
        .signature-wrap { margin-top: 10px; page-break-inside: avoid; }
        .signature-title { font-size: 11px; font-weight: 700; margin-bottom: 6px; }
        .signature-table { width: 100%; border-collapse: collapse; }
        .signature-table td { border: 1px dashed #9ca3af; padding: 8px; font-size: 9px; height: 62px; vertical-align: top; }
        .content { position: relative; z-index: 1; }
    </style>
</head>
<body>
    @php
        $modules = ['dashboard', 'cms', 'calendar', 'finance', 'users'];
        $actions = ['create', 'read', 'update', 'delete', 'export', 'publish'];
    @endphp
    <div class="watermark">INTERNAL / CONFIDENTIAL</div>

    <div class="fixed-header">
        <div class="header">
            <table class="header-row">
                <tr>
                    <td class="logo-cell">
                        @if (($logoDataUri ?? '') !== '')
                            <img src="{{ $logoDataUri }}" alt="PHN Logo" class="logo">
                        @endif
                    </td>
                    <td>
                        <div class="brand">{{ $companyName }}</div>
                        <div class="tagline">{{ $tagline }}</div>
                        <div class="meta">Document No: {{ $documentNumber ?? '-' }} • Role Permission Matrix Export • Generated at: {{ $generatedAt }} • Generated by: {{ $generatedBy ?? 'System' }}</div>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div class="fixed-footer">
        <div class="footer-box">
            <span>Document: {{ $documentNumber ?? '-' }}</span>
            <span>Classification: INTERNAL / CONFIDENTIAL</span>
            <span>Generated by {{ $generatedBy ?? 'System' }}</span>
        </div>
    </div>

    <div class="content">
    <div class="header" style="visibility:hidden; margin-bottom: 10px;">
        <table class="header-row">
            <tr>
                <td class="logo-cell">
                    @if (($logoDataUri ?? '') !== '')
                        <img src="{{ $logoDataUri }}" alt="PHN Logo" class="logo">
                    @endif
                </td>
                <td>
                    <div class="brand">{{ $companyName }}</div>
                    <div class="tagline">{{ $tagline }}</div>
                    <div class="meta">Role Permission Matrix Export • Generated at: {{ $generatedAt }} • Generated by: {{ $generatedBy ?? 'System' }}</div>
                </td>
            </tr>
        </table>
    </div>

    <div class="section-break">
        <div class="title">Role Basics & Dynamic Context</div>
        <table>
            <thead>
                <tr>
                    <th style="width: 12%;">Role</th>
                    <th style="width: 10%;">Slug</th>
                    <th style="width: 17%;">Description</th>
                    <th style="width: 9%;">Scope</th>
                    <th style="width: 9%;">Base Role</th>
                    <th style="width: 12%;">Override Add</th>
                    <th style="width: 12%;">Override Remove</th>
                    <th style="width: 11%;">Dynamic</th>
                    <th style="width: 8%;">Audit</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($roles as $role)
                    @php
                        $dynamic = is_array($role['dynamic'] ?? null) ? $role['dynamic'] : [];
                    @endphp
                    <tr>
                        <td>{{ $role['name'] ?? '-' }}<div class="small">Color: {{ $role['color_label'] ?? '-' }}</div></td>
                        <td>{{ $role['slug'] ?? '-' }}</td>
                        <td>{{ $role['description'] ?? '-' }}</td>
                        <td>{{ strtoupper((string) ($role['resource_scope'] ?? '-')) }}<div class="small">{{ $role['resource_department'] ?? '' }}</div></td>
                        <td>{{ $role['base_role_slug'] ?? '-' }}</td>
                        <td>{{ implode(', ', (array) ($role['override_add'] ?? [])) ?: '-' }}</td>
                        <td>{{ implode(', ', (array) ($role['override_remove'] ?? [])) ?: '-' }}</td>
                        <td>
                            Time: {{ $dynamic['time_start'] ?? '-' }} → {{ $dynamic['time_end'] ?? '-' }}<br>
                            Project: {{ $dynamic['project_scope'] ?? '-' }}<br>
                            IP: {{ $dynamic['office_ip_only'] ?? '-' }}
                        </td>
                        <td>{{ $role['updated_at'] ?? '-' }}<div class="small">By {{ $role['updated_by'] ?? '-' }}</div></td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    @foreach ($modules as $module)
        <div class="section-break">
            <div class="title">Module Grouping • <span class="module-name">{{ $module }}</span></div>
            <table>
                <thead>
                    <tr>
                        <th style="width: 14%;">Role</th>
                        @foreach ($actions as $action)
                            <th style="width: 8%;">{{ strtoupper($action) }}</th>
                        @endforeach
                        <th style="width: 26%;">Notes</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($roles as $role)
                        @php
                            $permissions = is_array($role['permissions'] ?? null) ? $role['permissions'] : [];
                            $moduleActions = is_array($permissions[$module] ?? null) ? $permissions[$module] : [];
                        @endphp
                        <tr>
                            <td>{{ $role['name'] ?? '-' }}<div class="small">{{ $role['slug'] ?? '-' }}</div></td>
                            @foreach ($actions as $action)
                                @php $enabled = (int) ($moduleActions[$action] ?? 0) === 1; @endphp
                                <td class="{{ $enabled ? 'yes' : 'no' }}">{{ $enabled ? 'ALLOW' : 'DENY' }}</td>
                            @endforeach
                            <td class="small">
                                Resource: {{ strtoupper((string) ($role['resource_scope'] ?? 'own_project')) }}{{ ($role['resource_department'] ?? '') !== '' ? ' / '.$role['resource_department'] : '' }}
                                @if (($role['base_role_slug'] ?? '') !== '')
                                    <br>Inherited from: {{ $role['base_role_slug'] }}
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    @endforeach

    <div class="signature-wrap">
        <div class="signature-title">Digital Signature Placeholder (Audit Compliance)</div>
        <table class="signature-table">
            <tr>
                <td>
                    <strong>Prepared By</strong><br>
                    Name: {{ $generatedBy ?? 'System' }}<br>
                    Date: {{ $generatedAt }}<br>
                    Signature Hash: ______________________
                </td>
                <td>
                    <strong>Reviewed By</strong><br>
                    Name: ______________________<br>
                    Date: ______________________<br>
                    Signature Hash: ______________________
                </td>
                <td>
                    <strong>Approved By</strong><br>
                    Name: ______________________<br>
                    Date: ______________________<br>
                    Signature Hash: ______________________
                </td>
            </tr>
        </table>
    </div>
    </div>
</body>
</html>
