<?php

use App\Http\Controllers\Dashboard\AnalyticsController;
use App\Http\Controllers\Dashboard\StoreOrderController;
use App\Http\Controllers\Dashboard\StoreProductController;
use App\Http\Controllers\Dashboard\UserManagementController;
use App\Http\Controllers\Dashboard\VideoController;
use App\Http\Controllers\Dashboard\WebsiteCmsBlogNewsController;
use App\Http\Controllers\Dashboard\WebsiteCmsGeneralController;
use App\Http\Controllers\Dashboard\WebsiteCmsHeaderController;
use App\Http\Controllers\Dashboard\WebsiteCmsLogoController;
use App\Http\Controllers\Dashboard\WebsiteCmsPagesController;
use App\Http\Controllers\Dashboard\WebsiteCmsPortfolioController;
use App\Http\Controllers\Dashboard\WebsiteCmsSliderVideoController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\StoreController;
use Illuminate\Support\Facades\Route;

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::post('/contact', [HomeController::class, 'submitContact'])->name('contact.submit');
Route::get('/about', [HomeController::class, 'about'])->name('page.about');
Route::get('/services', [HomeController::class, 'services'])->name('page.services');
Route::get('/faq', [HomeController::class, 'faq'])->name('page.faq');
Route::get('/store', [StoreController::class, 'index'])->name('store.index');
Route::get('/store/cart', [StoreController::class, 'cart'])->name('store.cart');
Route::post('/store/cart/update', [StoreController::class, 'updateCart'])->name('store.cart.update');
Route::post('/store/cart/{slug}/add', [StoreController::class, 'addToCart'])->name('store.cart.add');
Route::post('/store/cart/{slug}/remove', [StoreController::class, 'removeFromCart'])->name('store.cart.remove');
Route::post('/store/{slug}/purchase', [StoreController::class, 'purchase'])->name('store.purchase');
Route::get('/store/checkout', [StoreController::class, 'checkout'])->name('store.checkout');
Route::post('/store/checkout', [StoreController::class, 'checkoutPlaceOrder'])->name('store.checkout.place-order');
Route::get('/store/order/{orderCode}/success', [StoreController::class, 'orderSuccess'])->name('store.order.success');
Route::get('/store/payment/doku/return', [StoreController::class, 'dokuReturn'])->name('store.payment.doku.return');
Route::post('/store/payment/doku/notify', [StoreController::class, 'dokuNotify'])->name('store.payment.doku.notify');
Route::get('/download/{token}', [StoreController::class, 'downloadByToken'])->name('store.download.token');
Route::get('/store/{slug}', [StoreController::class, 'show'])->name('store.show');
Route::get('/blog', [HomeController::class, 'blogIndex'])->name('blog.index');
Route::get('/blog/{slug}', [HomeController::class, 'blogShow'])->name('blog.show');
Route::post('/blog/{slug}/comments', [HomeController::class, 'blogCommentStore'])->name('blog.comment.store');
Route::post('/blog/{slug}/like', [HomeController::class, 'blogLike'])->name('blog.like');
Route::get('/sitemap-blog.xml', [HomeController::class, 'blogSitemap'])->name('blog.sitemap');
Route::get('/privacy-policy', [HomeController::class, 'privacyPolicy'])->name('page.privacy-policy');
Route::get('/terms', [HomeController::class, 'terms'])->name('page.terms');
Route::get('/pages/{slug}', [HomeController::class, 'customPage'])->name('page.custom');
Route::get('/dashboard', [AnalyticsController::class, 'index'])->name('dashboard-analytics');
Route::get('/dashboard/website-cms/general', [WebsiteCmsGeneralController::class, 'index'])->name('dashboard-website-cms-general');
Route::post('/dashboard/website-cms/general', [WebsiteCmsGeneralController::class, 'update'])->name('dashboard-website-cms-general.update');
Route::post('/dashboard/website-cms/general/directus/push', [WebsiteCmsGeneralController::class, 'directusPush'])->name('dashboard-website-cms-general.directus.push');
Route::post('/dashboard/website-cms/general/directus/pull', [WebsiteCmsGeneralController::class, 'directusPull'])->name('dashboard-website-cms-general.directus.pull');
Route::post('/dashboard/website-cms/general/directus/provision', [WebsiteCmsGeneralController::class, 'directusProvision'])->name('dashboard-website-cms-general.directus.provision');
Route::get('/dashboard/website-cms/general/directus/blueprint', [WebsiteCmsGeneralController::class, 'downloadDirectusBlueprint'])->name('dashboard-website-cms-general.directus.blueprint');
Route::get('/dashboard/website-cms/general/directus/field-mapping', [WebsiteCmsGeneralController::class, 'downloadDirectusFieldMapping'])->name('dashboard-website-cms-general.directus.field-mapping');
Route::get('/dashboard/website-cms/logo', [WebsiteCmsLogoController::class, 'index'])->name('dashboard-website-cms-logo');
Route::post('/dashboard/website-cms/logo', [WebsiteCmsLogoController::class, 'update'])->name('dashboard-website-cms-logo.update');
Route::get('/dashboard/website-cms/header', [WebsiteCmsHeaderController::class, 'index'])->name('dashboard-website-cms-header');
Route::post('/dashboard/website-cms/header', [WebsiteCmsHeaderController::class, 'update'])->name('dashboard-website-cms-header.update');
Route::get('/dashboard/website-cms/slider-video', [WebsiteCmsSliderVideoController::class, 'index'])->name('dashboard-website-cms-slider-video');
Route::post('/dashboard/website-cms/slider-video', [WebsiteCmsSliderVideoController::class, 'update'])->name('dashboard-website-cms-slider-video.update');
Route::get('/dashboard/website-cms/pages', [WebsiteCmsPagesController::class, 'index'])->name('dashboard-website-cms-pages');
Route::post('/dashboard/website-cms/pages', [WebsiteCmsPagesController::class, 'update'])->name('dashboard-website-cms-pages.update');
Route::get('/dashboard/website-cms/portfolio', [WebsiteCmsPortfolioController::class, 'index'])->name('dashboard-website-cms-portfolio');
Route::post('/dashboard/website-cms/portfolio', [WebsiteCmsPortfolioController::class, 'update'])->name('dashboard-website-cms-portfolio.update');
Route::get('/dashboard/website-cms/blog-news', [WebsiteCmsBlogNewsController::class, 'index'])->name('dashboard-website-cms-blog-news');
Route::post('/dashboard/website-cms/blog-news', [WebsiteCmsBlogNewsController::class, 'update'])->name('dashboard-website-cms-blog-news.update');
Route::post('/dashboard/website-cms/blog-news/comments/{commentId}/moderate', [WebsiteCmsBlogNewsController::class, 'moderateComment'])->name('dashboard-website-cms-blog-news.comments.moderate');
Route::get('/dashboard/store/product', [StoreProductController::class, 'index'])->name('dashboard-store-product');
Route::post('/dashboard/store/product', [StoreProductController::class, 'update'])->name('dashboard-store-product.update');
Route::get('/dashboard/store/orders', [StoreOrderController::class, 'index'])->name('dashboard-store-order');
Route::post('/dashboard/store/orders/{orderCode}/status', [StoreOrderController::class, 'updateStatus'])->name('dashboard-store-order.update-status');
Route::middleware(['admin.role'])->group(function (): void {
    Route::get('/dashboard/user', [UserManagementController::class, 'index'])->name('dashboard-user-management');
    Route::get('/dashboard/user/create', [UserManagementController::class, 'create'])->name('dashboard-user-create');
    Route::post('/dashboard/user/create', [UserManagementController::class, 'store'])->name('dashboard-user-create.store');
    Route::get('/dashboard/user/role', [UserManagementController::class, 'role'])->name('dashboard-user-role');
    Route::post('/dashboard/user/role', [UserManagementController::class, 'roleStore'])->name('dashboard-user-role.store');
    Route::post('/dashboard/user/role/rollback', [UserManagementController::class, 'roleRollback'])->name('dashboard-user-role.rollback');
    Route::get('/dashboard/user/role/export/csv', [UserManagementController::class, 'roleExportCsv'])->name('dashboard-user-role.export-csv');
    Route::get('/dashboard/user/role/export/pdf', [UserManagementController::class, 'roleExportPdf'])->name('dashboard-user-role.export-pdf');
    Route::post('/dashboard/user/{user}/update', [UserManagementController::class, 'update'])->name('dashboard-user-management.update');
    Route::post('/dashboard/user/{user}/toggle-suspend', [UserManagementController::class, 'toggleSuspend'])->name('dashboard-user-management.toggle-suspend');
    Route::post('/dashboard/user/{user}/reset-password', [UserManagementController::class, 'resetPassword'])->name('dashboard-user-management.reset-password');
});
Route::get('/activate/{userId}/{token}', [UserManagementController::class, 'activate'])->name('dashboard-user-activate');
Route::post('/dashboard/media/videos/upload', [VideoController::class, 'upload'])->name('dashboard-media-videos.upload');
Route::get('/dashboard/media/videos/{id}', [VideoController::class, 'show'])->name('dashboard-media-videos.show');
Route::post('/dashboard/media/videos/{id}/retry', [VideoController::class, 'retry'])->name('dashboard-media-videos.retry');
