<?php

return [
    'disk' => env('MEDIA_DISK', 'public'),
    'ffmpeg' => env('FFMPEG_BIN', 'ffmpeg'),
    'ffprobe' => env('FFPROBE_BIN', 'ffprobe'),
    'video_transcode' => [
        'engine' => env('VIDEO_TRANSCODE_ENGINE', 'ffmpeg'),
        'codec' => env('VIDEO_TRANSCODE_CODEC', 'vp9'),
        'gstreamer_bin' => env('GSTREAMER_BIN', 'gst-launch-1.0'),
        'handbrake_bin' => env('HANDBRAKE_BIN', 'HandBrakeCLI'),
        'profiles' => [
            'default' => [
                'codec' => env('VIDEO_TRANSCODE_CODEC', 'vp9'),
                'crf' => 31,
                'video_bitrate' => '0',
                'audio_bitrate' => '128k',
                'cpu_used' => 1,
                'ffmpeg_deadline' => 'good',
                'ffmpeg_threads' => 0,
                'gstreamer_deadline' => 1,
                'gstreamer_cpu_used' => 2,
                'handbrake_quality' => 28,
                'max_execution_time' => 0,
                'process_timeout_seconds' => 0,
            ],
            'slider' => [
                'codec' => 'vp9',
                'crf' => 36,
                'video_bitrate' => '900k',
                'audio_bitrate' => '96k',
                'cpu_used' => 8,
                'ffmpeg_deadline' => 'realtime',
                'ffmpeg_threads' => 0,
                'gstreamer_deadline' => 2,
                'gstreamer_cpu_used' => 4,
                'handbrake_quality' => 32,
                'max_execution_time' => 0,
                'process_timeout_seconds' => 0,
            ],
            'slider_tablet' => [
                'codec' => 'vp9',
                'crf' => 38,
                'video_bitrate' => '700k',
                'audio_bitrate' => '80k',
                'cpu_used' => 8,
                'ffmpeg_deadline' => 'realtime',
                'ffmpeg_threads' => 0,
                'gstreamer_deadline' => 3,
                'gstreamer_cpu_used' => 6,
                'handbrake_quality' => 34,
                'max_execution_time' => 0,
                'process_timeout_seconds' => 0,
            ],
            'portfolio' => [
                'codec' => env('VIDEO_TRANSCODE_CODEC_PORTFOLIO', 'vp9'),
                'crf' => 28,
                'video_bitrate' => '0',
                'audio_bitrate' => '128k',
                'cpu_used' => 1,
                'ffmpeg_deadline' => 'good',
                'ffmpeg_threads' => 0,
                'gstreamer_deadline' => 1,
                'gstreamer_cpu_used' => 2,
                'handbrake_quality' => 24,
                'max_execution_time' => 0,
                'process_timeout_seconds' => 0,
            ],
            'blog' => [
                'codec' => env('VIDEO_TRANSCODE_CODEC_BLOG', 'vp9'),
                'crf' => 29,
                'video_bitrate' => '0',
                'audio_bitrate' => '112k',
                'cpu_used' => 2,
                'ffmpeg_deadline' => 'good',
                'ffmpeg_threads' => 0,
                'gstreamer_deadline' => 1,
                'gstreamer_cpu_used' => 3,
                'handbrake_quality' => 26,
                'max_execution_time' => 0,
                'process_timeout_seconds' => 0,
            ],
        ],
    ],
    'cdn_base_url' => env('CDN_BASE_URL', env('APP_URL').'/storage'),
    'hls_segment_seconds' => (int) env('HLS_SEGMENT_SECONDS', 4),
];
