<?php

return [
    'creatorName' => 'Production House Nusantara',
    'creatorUrl' => env('APP_URL', 'http://localhost'),
    'templateName' => 'PH NUSANTARA',
    'templateSuffix' => 'Sneat Laravel',
    'templateVersion' => '3.0.0',
    'templateFree' => true,
    'templateDescription' => 'Dashboard operasional Production House Nusantara.',
    'templateKeyword' => 'dashboard, production house, studio',
    'licenseUrl' => '#',
    'livePreview' => '#',
    'productPage' => env('APP_URL', 'http://localhost').'/dashboard',
    'support' => '#',
    'adminTemplates' => '#',
    'bootstrapDashboard' => '#',
    'ogTitle' => 'PH NUSANTARA',
    'ogImage' => '',
    'ogType' => 'website',
    'documentation' => '#',
    'repository' => '#',
    'gitRepo' => '#',
    'gitRepoAccess' => '#',
    'githubFreeUrl' => '#',
    'facebookUrl' => '#',
    'twitterUrl' => '#',
    'githubUrl' => '#',
    'dribbbleUrl' => '#',
    'instagramUrl' => '#',
];
